trigger:
#- main
- none

jobs:
- job: deploy_application
  pool:
    vmImage: 'windows-latest'
  steps:
  - task: DotNetCoreCLI@2
    displayName: Restore
    inputs:
      command: 'restore'
      projects: '**/*.csproj'
  - task: AzureAppServiceManage@0
    displayName: Install Contrast Extension
    inputs:
      action: 'Install Extensions'
      azureSubscription: 'ATARC Zero Trust Solution (275fde5b-989e-4985-aad3-51f9e39899f5)'
      resourceGroupName: 'dotnet7-web'
      webAppName: 'dotnet-7-winapp'
      extensionsList: 'Contrast.NetCore.Azure.SiteExtension'
  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      command: 'build'
  - task: DotNetCoreCLI@2
    displayName: Publish
    inputs:
      command: publish
      publishWebProjects: True
      arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)'
      zipAfterPublish: True
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'drop'
      publishLocation: 'Container'
  - task: AzureRmWebAppDeployment@4
    inputs:
      ConnectionType: 'AzureRM'
      azureSubscription: 'ATARC Zero Trust Solution (275fde5b-989e-4985-aad3-51f9e39899f5)'
      appType: 'webApp'
      WebAppName: 'dotnet-7-winapp'
      packageForLinux: '$(Build.ArtifactStagingDirectory)/**/*.zip'