trigger:
- main

pool:
  vmImage: 'windows-latest'

steps:
- task: DotNetCoreCLI@2
  displayName: Restore
  inputs:
    command: 'restore'
    projects: '**/*.csproj'
- task: AzureAppServiceManage@0
  displayName: Install Contrast Extension
  inputs:
    action: 'Install Extensions'
    azureSubscription: 'ATARC Zero Trust Solution'
    resourceGroupName: 'sweller-res-grp'
    webAppName: 'sweller-app2'
    extensionsList: 'Contrast.NetCore.Azure.SiteExtension'

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: 'build'
- task: DotNetCoreCLI@2
  displayName: Publish
  inputs:
    command: publish
    publishWebProjects: True
    arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)'
    zipAfterPublish: True

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'